### ISSUE TITLE
Crash: Out of memory

### ISSUE THREAD

**Issue by pilzinho** [Cinegy/Cinecoder.Samples#23] opened 2020-02-06 15:49 UTC
We are trying to get our Daniel2 implementation based on this repository production ready and are performing a lot of stress tests.
Theoretically our application can load an unlimited number of Daniel2 videos and display them side by side. But at some point this always leads to a crash of the application. We would like to be able to present feedback to the user that no more videos can be loaded.
For this reason we are already catching all the errors that can happen in the DecodeDaniel2 and Render classes (every function that may return a negative (H)result or CUDA error) and prevent loading the video or close it if it's already decoding/playing.
But we still have crashes that we cannot catch often with the following call stack:

___d2cudalib returns error -1002: out of memory ((null), fffffc16h) at D2D.cpp (193)
out of memory ((null), fffffc16h) at d2_decoder_impl.h (410)
CUDA decoder creation failure, using CPU decoder instead ((null), fffffc16h) at d2_decoder_impl.h_ (376)__  

Maybe with the help of this call stack you can locate something in your code that might result in these crashes.

**Comment by nick-velichko** [comment] 2020-02-06 18:34
Hello,

Could you provide a bit more information about your case?
What the GPU card do you use?
How many streams you can play before crash?
What is the stream format? resolution, chroma_format, etc...

Actually, as you can see, the error does happen because you ran out of GPU memory in your application, and, which is worse, the CUDA error may propagate into any other decoder currently working within the same CUDA context, so it is not easy to detect what and where did particularly crash.

We need at least to be able to reproduce the case to find out what can go wrong.

**Comment by lewk2** [comment] 2020-05-20 21:45
closing as abandoned

**Closed as completed by lewk2** 2020-05-20 21:45 UTC
Labels: question, problem
