### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by 11020409** [Cinegy/Cinecoder.Samples#19] opened 2019-07-06 01:22 UTC
I'm getting an Access Violation here:

C++:
`piFactory->CreateInstance(clsidDecoder, IID_ICC_VideoDecoder, (IUnknown**)&m_pVideoDec)`

When trying to create MPEG decoder using the sample **Daniel2.SimplePlayerGL**

When using C#:
Ir seems that Cinecoder.Interop.dll is only x86

**Comment by lewk2** [comment] 2019-11-28 01:28
We suspect this was an exception caused by an expired license. We have added clearer exceptions now, certainly the interop library works in 64.

I will close this issue, since we suspect the problem was just the license. If you still have problems, please re-open.

**Closed as completed by lewk2** 2019-11-28 01:28 UTC
